{% set name = "pyarrow-hotfix" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyarrow_hotfix-{{ version }}.tar.gz
  sha256: 59399cd58bdd978b2e42816a4183a55c6472d4e33d183351b6069f11ed42661d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyarrow >=0.14

test:
  imports:
    - pyarrow_hotfix
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pitrou/pyarrow-hotfix
  summary: Hotfix older pyarrow releases to avoid the CVE fixed in 14.0.1
  dev_url: https://github.com/pitrou/pyarrow-hotfix
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
    - jorisvandenbossche
